apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-service
  annotations:
    mia-platform.eu/version: 13.6.0
    apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
    apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
    fluentbit.io/parser: pino
  labels:
    app: echo-service
    app.kubernetes.io/name: echo-service
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: custom
    app.kubernetes.io/part-of: github-app-test
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: development
    mia-platform.eu/tenant: rocket-playground
    mia-platform.eu/log-type: mia-json
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-service
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 1
  template:
    metadata:
      annotations:
        mia-platform.eu/version: 13.6.0
        apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
        fluentbit.io/parser: pino
      labels:
        app: echo-service
        app.kubernetes.io/name: echo-service
        app.kubernetes.io/version: latest
        app.kubernetes.io/component: custom
        app.kubernetes.io/part-of: github-app-test
        app.kubernetes.io/managed-by: mia-platform
        mia-platform.eu/stage: development
        mia-platform.eu/tenant: rocket-playground
        mia-platform.eu/log-type: mia-json
    spec:
      imagePullSecrets:
        - name: nexus-gcloud
      terminationGracePeriodSeconds: 30
      containers:
        - name: echo-service
          image: davidebianchi/echo-service
          imagePullPolicy: Always
          resources:
            limits:
              memory: 150Mi
              cpu: 100m
            requests:
              memory: 150Mi
              cpu: 100m
          volumeMounts: []
          ports:
            - name: http
              containerPort: 3000
          args: []
          env:
            - name: HTTP_PORT
              value: '3000'
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      volumes: []
      hostIPC: false
      hostNetwork: false
      hostPID: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
