apiVersion: v1
kind: Service
metadata:
  name: kafka2rest-service
  annotations:
    mia-platform.eu/version: 14.1.0
  labels:
    app: kafka2rest-service
    app.kubernetes.io/name: kafka2rest-service
    app.kubernetes.io/version: 1.1.1
    app.kubernetes.io/component: custom
    app.kubernetes.io/part-of: github-app-test
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: development
    mia-platform.eu/tenant: rocket-playground
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: null
  selector:
    app: kafka2rest-service
